package se.jh.glosa.vo;

public enum Tempi {
    INFINITIV, GERUNDIUM, PERFEKTPARTICIP,

    INDIKATIVPRESENS, INDIKATIVPRETERITUM, INDIKATIVIMPERFEKT, INDIKATIVFUTURUM, INDIKATIVKONDITIONALIS,
    INDIKATIVPERFEKT, INDIKATIVPLUSKVAMPERFEKT, INDIKATIVSAMMANSATTFUTURUM, INDIKATIVSAMMANSATTKONDITIONALIS,

    KONJUNKTIVPRESENS, KONJUNKTIVIMPERFEKT, KONJUNKTIVPERFEKT, KONJUNKTIVPLUSKVAMPERFEKT,

    IMPERATIVJAKANDE, IMPERATIVNEKANDE
}
